# Configuration SonarCloud — TP Analyse de code

sonar.projectKey=rayanziani
sonar.organization=RayanZiani

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/.gradle/**,**/gradle/**,**/*.png,**/*.jpg,**/*.webp,**/*.jar,**/*.apk,**/*.dex,**/*.class

sonar.java.binaries=**/build/intermediates/javac/**/classes,**/build/tmp/kotlin-classes/**

sonar.kotlin.detection.reportPaths=**/build/reports/detekt/*.xml

sonar.tests=app/src/test,app/src/androidTest
sonar.test.inclusions=**/*Test*.java,**/*Test*.kt
